server:
  port: 8081
#数据源配置 这里是c3p0数据源配置 注意冒号后面要有空格
c3p0: 
  jdbcUrl: jdbc:mysql://localhost:3306/shiroproject?useUnicode=true&characterEncoding=utf-8&useSSL=true&useAffectedRows=true
  user: root
  password: 123456
  driverClass: com.mysql.jdbc.Driver
  minPoolSize: 5
  maxPoolSize: 60
  maxIdleTime: 1800000
  acquireIncrement: 3
  maxStatements: 1000
  initialPoolSize: 3
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false
mybatis:
  # 配置类型别名
  typeAliasesPackage: com.shiroDemo.shiroProject.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mappers/mapper/*.xml
  # 加载全局的配置文件
  configLocation: classpath:mappers/mybatis-config.xml
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    enabled: false
  mvc: 
    static-path-pattern: /static/**
  freemarker: 
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    template-loader-path: classpath:/templates/
    suffix: .html
  resources: 
    chain: 
      strategy: 
        content: 
          enabled: true
          paths: /static/**
  redis:
    database: 1  # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password: aA123456  # Redis服务器连接密码（默认为空）
    
  # JavaMailSender 邮件发送的配置
  mail: 
    protocol: smtp
    host: smtp.qq.com
    port: 465
    username: 846656938@qq.com
    password: dgbqplhhlvsebdaj
    default-encoding: UTF-8
    properties: 
      mail: 
        smtp: # 如果不加下面3句,会报530错误
          auth: true
          ssl: 
            enable: true
          starttls: 
            enable: true
            required: true

mail:    
  fromMail: 
    addr: 846656938@qq.com  # 表明发送者（可以不写，个人喜好）
    